name: Windows RDP Free

on: 
  workflow_dispatch:   # cho phép bạn bấm nút Run workflow để chạy

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Cài đặt RDP & Chrome
      run: |
        # Tạo user để login
        net user runneradmin MyPassword123! /add
        net localgroup administrators runneradmin /add

        # Bật Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

        # Bật firewall cho RDP
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

        # Cho phép xác thực RDP qua password
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -name "LimitBlankPasswordUse" -Value 0

        # Cài đặt Google Chrome
        Invoke-WebRequest https://dl.google.com/chrome/install/latest/chrome_installer.exe -OutFile chrome_installer.exe
        Start-Process chrome_installer.exe -ArgumentList "/silent /install" -NoNewWindow -Wait

        echo "✅ Đã cài Chrome + bật RDP thành công"

    - name: Hiển thị IP công khai
      run: |
        Invoke-RestMethod ifconfig.me
